export const PERMISSIONS = Object.freeze({
  APPOINTMENTS_CANCEL: "appointments.cancel",
  APPOINTMENTS_CREATE: "appointments.create",
  APPOINTMENTS_READ_ALL: "appointments.read_all",
  APPOINTMENTS_READ_OWN: "appointments.read_own",
  APPOINTMENTS_UPDATE: "appointments.update",
  APPOINTMENTS_UPDATE_OWN_STATUS: "appointments.update_own_status",
  CUSTOMERS_MANAGE: "customers.manage",
  CUSTOMERS_READ: "customers.read",
  MEDICAL_RECORDS_READ_ASSIGNED: "medical_records.read_assigned",
  MEDICAL_RECORDS_WRITE_ASSIGNED: "medical_records.write_assigned",
  PATIENTS_MANAGE_BASIC: "patients.manage_basic",
  PATIENTS_READ_BASIC: "patients.read_basic",
  PRESCRIPTIONS_CREATE: "prescriptions.create",
  PRESCRIPTIONS_READ_ASSIGNED: "prescriptions.read_assigned",
  PRESCRIPTIONS_READ_FOR_SALE: "prescriptions.read_for_sale",
  PRODUCTS_MANAGE: "products.manage",
  PRODUCTS_READ: "products.read",
  REPORTS_READ: "reports.read",
  SALES_CREATE: "sales.create",
  SALES_DISCOUNTS_AUTHORIZE: "sales.discounts_authorize",
  SALES_MERCADO_PAGO_CHECKOUT: "sales.mercado_pago_checkout",
  SALES_PAYMENTS_REGISTER: "sales.payments_register",
  SALES_READ: "sales.read",
  SALES_REPORTS_READ: "sales.reports_read",
  SALES_UPDATE: "sales.update",
  SCHEDULES_MANAGE_ALL: "schedules.manage_all",
  SCHEDULES_MANAGE_OWN: "schedules.manage_own",
  SCHEDULES_READ: "schedules.read",
  USERS_ASSIGN_ROLES: "users.assign_roles",
  USERS_CREATE: "users.create",
  USERS_DEACTIVATE: "users.deactivate",
  USERS_READ: "users.read",
  USERS_UPDATE: "users.update",
});

export const PERMISSION_CODES = Object.freeze(Object.values(PERMISSIONS));
